name: Fetch Repository & Branches
on: [push]

jobs:
  checkout-action:
    runs-on: ubuntu-latest
    steps:
      - name: List Files Before
        run: ls

      - uses: action/checkout@v3

      - name: List Files After
        run: ls

  checkout-d-files:
    runs-on: ubuntu-latest

    steps:
      - name: List Files Before
        run: ls
      - name: Checkout Repo
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout main

      - name: List Files After
        run: ls
